import re
import time
import asyncio
import logging
from typing import Optional, Union, Dict, Any, List, BinaryIO, AsyncGenerator
from pathlib import Path

from config.settings import settings
from voice.stt import BaseSTTService, FasterWhisperSTTService
from voice.tts import BaseTTSService, EdgeTTSService, clean_text_for_speech, split_sentences
from rag.chatbot import SurfacesChatbot
from rag.prompt import WELCOME_MESSAGE

logger = logging.getLogger(__name__)


def check_voice_fast_path(text: str) -> Optional[str]:
    """Check for instant conversational greetings, thanks, or identity responses.
    
    Bypasses expensive vector retrieval and LLM calls, returning in < 1.2s total.
    """
    if not text:
        return None
    cleaned = text.lower().strip("?!., ")
    if cleaned in (
        "hello", "hi", "hey", "good morning", "good afternoon",
        "hi sophie", "hello sophie", "hello there", "how are you"
    ):
        return WELCOME_MESSAGE
    if cleaned in ("what is your name", "what's your name", "who are you"):
        return "Hello! I'm Sophie, the AI assistant for Surfaces Tiles UK. How can I help you find the right tiles today?"
    if cleaned in ("thank you", "thanks", "thank you so much", "thanks sophie"):
        return "You're very welcome! Let me know if you need any help with tile styles, measurements, or ordering free samples."
    return None


class VoiceAssistantService:
    """Orchestrates end-to-end Voice Assistant interactions:
    User Audio -> Faster-Whisper STT (CPU int8) -> RAG Chatbot -> Neural Edge-TTS
    Supports both low-latency sentence streaming and traditional full-turn chat.
    """

    def __init__(
        self,
        stt_service: Optional[BaseSTTService] = None,
        tts_service: Optional[BaseTTSService] = None,
        chatbot: Optional[SurfacesChatbot] = None
    ):
        self.stt_service = stt_service or FasterWhisperSTTService()
        self.tts_service = tts_service or EdgeTTSService()
        self.chatbot = chatbot

    async def stream_voice_chat(
        self,
        audio_input: Union[str, Path, bytes, BinaryIO],
        session_id: str,
        chatbot: SurfacesChatbot,
        history: Optional[List[Any]] = None,
        language: Optional[str] = None,
        cancel_event: Optional[asyncio.Event] = None
    ) -> AsyncGenerator[Dict[str, Any], None]:
        """Low-latency streaming voice chat pipeline.
        
        Yields events:
        1. 'transcript': Transcribed user speech text immediately after STT (~1.0s)
        2. 'token': AI text delta tokens as generated by Gemini
        3. 'audio_chunk': Sentence-by-sentence synthesized audio MP3 chunks
        4. 'sources' & 'products': Discovered tile recommendations & cards
        5. 'done': Final aggregated response, session ID, and complete timings
        """
        start_time = time.time()

        # Step 1: STT via Faster-Whisper (in-memory stream, no disk I/O)
        stt_result = self.stt_service.transcribe(audio_input, language=language)
        transcribed_text = (stt_result.get("text") or "").strip()
        stt_latency = stt_result.get("latency_seconds", 0)

        logger.info(f"[VoiceAssistant Stream] Transcribed in {stt_latency:.2f}s: '{transcribed_text}'")

        # Emit transcript event immediately so frontend displays the user bubble
        yield {
            "event": "transcript",
            "text": transcribed_text,
            "session_id": session_id,
            "stt_latency": stt_latency
        }

        # Handle empty/unintelligible audio
        if not transcribed_text:
            empty_msg = "I couldn't clearly hear or understand the audio. Could you please try speaking again?"
            tts_res = await self.tts_service.synthesize(empty_msg)
            yield {
                "event": "audio_chunk",
                "chunk_index": 0,
                "text": empty_msg,
                "audio_base64": tts_res["audio_base64"],
                "audio_format": "mp3",
                "is_final": True
            }
            yield {
                "event": "done",
                "answer": empty_msg,
                "session_id": session_id,
                "sources": [],
                "products": [],
                "timings": {
                    "stt_seconds": stt_latency,
                    "rag_seconds": 0.0,
                    "tts_seconds": tts_res.get("latency_seconds", 0),
                    "total_seconds": round(time.time() - start_time, 3)
                }
            }
            return

        from api.session_manager import session_manager

        if history:
            resolved_history = history[-settings.max_chat_history:]
            session_manager.set_history(session_id, resolved_history)
        else:
            resolved_history = session_manager.get_history(session_id)

        # Step 2: Check conversational fast-path
        fast_answer = check_voice_fast_path(transcribed_text)
        if fast_answer:
            tts_res = await self.tts_service.synthesize(fast_answer)
            session_manager.add_turn(
                session_id=session_id,
                user_message=transcribed_text,
                assistant_response=fast_answer
            )
            yield {
                "event": "audio_chunk",
                "chunk_index": 0,
                "text": fast_answer,
                "audio_base64": tts_res["audio_base64"],
                "audio_format": "mp3",
                "is_final": True
            }
            yield {
                "event": "done",
                "answer": fast_answer,
                "session_id": session_id,
                "sources": [],
                "products": [],
                "timings": {
                    "stt_seconds": stt_latency,
                    "rag_seconds": 0.0,
                    "tts_seconds": tts_res.get("latency_seconds", 0),
                    "total_seconds": round(time.time() - start_time, 3)
                }
            }
            return

        # Step 3: Stream AI output and pipeline sentence synthesis
        rag_start = time.time()
        token_accumulator = []
        sentence_buffer = ""
        synthesized_sentences = []
        raw_sources = []
        raw_products = []
        chunk_counter = 0
        first_sentence_sent = False

        stream_gen = chatbot.stream_answer_question(
            message=transcribed_text,
            history=resolved_history
        )

        for chunk in stream_gen:
            if cancel_event and cancel_event.is_set():
                logger.info(f"[VoiceAssistant Stream] Stream cancelled by cancel_event during token generation")
                return
            evt = chunk.get("event")
            if evt == "sources":
                raw_sources = chunk.get("sources", [])
                yield {"event": "sources", "sources": raw_sources}
            elif evt == "products":
                raw_products = chunk.get("products", [])
                yield {"event": "products", "products": raw_products}
            elif evt == "token":
                delta = chunk.get("delta", "")
                token_accumulator.append(delta)
                sentence_buffer += delta
                yield {"event": "token", "delta": delta}

                # When the first sentence is formed, synthesize and emit immediately!
                if not first_sentence_sent:
                    # Detect sentence terminal (. ? ! or newline)
                    match = re.search(r'([.?!])(\s+|\n|$)', sentence_buffer)
                    if match:
                        end_pos = match.end()
                        s1 = sentence_buffer[:end_pos].strip()
                        # Ensure sentence has enough substance to speak cleanly
                        if len(s1.split()) >= 3 or ("." in s1 and len(s1) > 15):
                            first_sentence_sent = True
                            sentence_buffer = sentence_buffer[end_pos:]
                            if cancel_event and cancel_event.is_set():
                                return
                            try:
                                tts_s1 = await self.tts_service.synthesize(s1)
                                if cancel_event and cancel_event.is_set():
                                    return
                                yield {
                                    "event": "audio_chunk",
                                    "chunk_index": chunk_counter,
                                    "text": s1,
                                    "audio_base64": tts_s1["audio_base64"],
                                    "audio_format": "mp3",
                                    "is_final": False
                                }
                                synthesized_sentences.append(s1)
                                chunk_counter += 1
                            except Exception as tts_err:
                                logger.warning(f"Error synthesizing first sentence: {tts_err}")

            elif evt == "done":
                break

        if cancel_event and cancel_event.is_set():
            return

        full_answer = "".join(token_accumulator).strip()
        if not full_answer:
            full_answer = "We have a wide range of luxury porcelain and ceramic tiles. Could you tell me a little more about the space you're looking to tile?"

        rag_latency = time.time() - rag_start

        # Process any remaining text in sentence_buffer or full_answer
        remaining_sentences = []
        if first_sentence_sent:
            remaining_text = sentence_buffer.strip()
            if remaining_text:
                remaining_sentences = split_sentences(remaining_text)
        else:
            remaining_sentences = split_sentences(full_answer)

        # Synthesize remaining sentences sequentially into queue
        for sentence in remaining_sentences:
            if cancel_event and cancel_event.is_set():
                return
            clean_s = sentence.strip()
            if not clean_s:
                continue
            try:
                tts_chunk = await self.tts_service.synthesize(clean_s)
                yield {
                    "event": "audio_chunk",
                    "chunk_index": chunk_counter,
                    "text": clean_s,
                    "audio_base64": tts_chunk["audio_base64"],
                    "audio_format": "mp3",
                    "is_final": False
                }
                synthesized_sentences.append(clean_s)
                chunk_counter += 1
            except Exception as e:
                logger.warning(f"Error synthesizing sentence chunk: {e}")

        # Update session memory
        session_manager.add_turn(
            session_id=session_id,
            user_message=transcribed_text,
            assistant_response=full_answer
        )

        total_latency = time.time() - start_time
        logger.info(
            f"[VoiceAssistant Stream] Completed in {total_latency:.2f}s "
            f"(STT: {stt_latency:.2f}s, RAG: {rag_latency:.2f}s, Chunks: {chunk_counter})"
        )

        yield {
            "event": "done",
            "answer": full_answer,
            "session_id": session_id,
            "sources": raw_sources,
            "products": raw_products,
            "timings": {
                "stt_seconds": round(stt_latency, 3),
                "rag_seconds": round(rag_latency, 3),
                "total_seconds": round(total_latency, 3),
                "chunks_count": chunk_counter
            }
        }

    async def process_voice_chat(
        self,
        audio_input: Union[str, Path, bytes, BinaryIO],
        session_id: str,
        chatbot: SurfacesChatbot,
        history: Optional[List[Any]] = None,
        language: Optional[str] = None
    ) -> Dict[str, Any]:
        """Execute the optimized non-streaming voice interaction pipeline."""
        start_time = time.time()

        # Step 1: STT via Faster-Whisper (in-memory stream, no disk I/O)
        stt_result = self.stt_service.transcribe(audio_input, language=language)
        transcribed_text = (stt_result.get("text") or "").strip()
        stt_latency = stt_result.get("latency_seconds", 0)

        logger.info(f"[VoiceAssistant] Transcribed user audio in {stt_latency:.2f}s: '{transcribed_text}'")

        if not transcribed_text:
            empty_msg = "I couldn't clearly hear or understand the audio. Could you please try speaking again?"
            tts_res = await self.tts_service.synthesize(empty_msg)
            return {
                "transcribed_text": "",
                "response_text": empty_msg,
                "audio_base64": tts_res["audio_base64"],
                "audio_format": "mp3",
                "sources": [],
                "products": [],
                "session_id": session_id,
                "timings": {
                    "stt_seconds": stt_latency,
                    "rag_seconds": 0.0,
                    "tts_seconds": tts_res.get("latency_seconds", 0),
                    "total_seconds": round(time.time() - start_time, 3)
                }
            }

        from api.session_manager import session_manager

        if history:
            resolved_history = history[-settings.max_chat_history:]
            session_manager.set_history(session_id, resolved_history)
        else:
            resolved_history = session_manager.get_history(session_id)

        # Step 2: Check conversational fast-path
        fast_answer = check_voice_fast_path(transcribed_text)
        if fast_answer:
            tts_result = await self.tts_service.synthesize(fast_answer)
            session_manager.add_turn(
                session_id=session_id,
                user_message=transcribed_text,
                assistant_response=fast_answer
            )
            return {
                "transcribed_text": transcribed_text,
                "response_text": fast_answer,
                "audio_base64": tts_result["audio_base64"],
                "audio_format": "mp3",
                "sources": [],
                "products": [],
                "session_id": session_id,
                "timings": {
                    "stt_seconds": stt_latency,
                    "rag_seconds": 0.0,
                    "tts_seconds": tts_result.get("latency_seconds", 0),
                    "total_seconds": round(time.time() - start_time, 3)
                }
            }

        # Step 3: RAG Chatbot query
        rag_start = time.time()
        chatbot_result = chatbot.answer_question(
            message=transcribed_text,
            history=resolved_history
        )
        rag_latency = time.time() - rag_start

        response_text = chatbot_result.get("answer", "")
        raw_sources = chatbot_result.get("sources", [])
        raw_products = chatbot_result.get("products", [])

        # Step 4: Text-to-Speech (TTS) via Neural Edge-TTS
        tts_result = await self.tts_service.synthesize(response_text)

        # Step 5: Update session memory
        session_manager.add_turn(
            session_id=session_id,
            user_message=transcribed_text,
            assistant_response=response_text
        )

        total_latency = time.time() - start_time
        logger.info(
            f"[VoiceAssistant] Completed full pipeline in {total_latency:.2f}s "
            f"(STT: {stt_latency:.2f}s, RAG: {rag_latency:.2f}s, TTS: {tts_result.get('latency_seconds'):.2f}s)"
        )

        return {
            "transcribed_text": transcribed_text,
            "response_text": response_text,
            "audio_base64": tts_result["audio_base64"],
            "audio_format": "mp3",
            "sources": raw_sources,
            "products": raw_products,
            "session_id": session_id,
            "timings": {
                "stt_seconds": stt_latency,
                "rag_seconds": round(rag_latency, 3),
                "tts_seconds": tts_result.get("latency_seconds", 0),
                "total_seconds": round(total_latency, 3)
            }
        }
