import json
import logging
import os
import re
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import BackgroundTasks

from config.settings import settings

logger = logging.getLogger(__name__)

# Fallback background executor for non-FastAPI or thread-offloaded operations
_executor = ThreadPoolExecutor(max_workers=2, thread_name_prefix="interaction_logger")


def get_logs_dir() -> Path:
    """Return the configured logs directory, ensuring it exists."""
    logs_dir = getattr(settings, "logs_dir", settings.base_dir / "logs")
    logs_dir.mkdir(parents=True, exist_ok=True)
    return logs_dir


def _generate_log_filename(timestamp: datetime, logs_dir: Path) -> Path:
    """
    Generate a timestamp-based filename like 2026-09-09-133045.txt.
    If a collision occurs within the same second, append microsecond or numeric suffix.
    """
    base_name = timestamp.strftime("%Y-%m-%d-%H%M%S")
    candidate = logs_dir / f"{base_name}.txt"
    if not candidate.exists():
        return candidate

    # Append microsecond
    candidate = logs_dir / f"{base_name}_{timestamp.microsecond:06d}.txt"
    if not candidate.exists():
        return candidate

    # Increment counter suffix as last fallback
    counter = 1
    while True:
        candidate = logs_dir / f"{base_name}_{timestamp.microsecond:06d}_{counter}.txt"
        if not candidate.exists():
            return candidate
        counter += 1


def format_interaction_log(
    timestamp: datetime,
    user_input: str,
    internal_response: Any,
    ai_response: str,
    user_response: Any,
) -> str:
    """Format interaction details into a human-readable and structured text log."""
    formatted_time = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    iso_time = timestamp.isoformat()

    # Format internal/system response
    internal_str = ""
    if isinstance(internal_response, (dict, list)):
        try:
            internal_str = json.dumps(internal_response, indent=2, default=str)
        except Exception:
            internal_str = str(internal_response)
    else:
        internal_str = str(internal_response) if internal_response is not None else "N/A"

    # Format user response (payload actually sent to user)
    user_resp_str = ""
    if isinstance(user_response, (dict, list)):
        try:
            user_resp_str = json.dumps(user_response, indent=2, default=str)
        except Exception:
            user_resp_str = str(user_response)
    else:
        user_resp_str = str(user_response) if user_response is not None else "N/A"

    ai_resp_str = str(ai_response) if ai_response is not None else "N/A"

    log_content = (
        "================================================================================\n"
        f"CHATBOT INTERACTION LOG\n"
        "================================================================================\n"
        f"Date and Time of Interaction: {formatted_time} (ISO: {iso_time})\n\n"
        "--------------------------------------------------------------------------------\n"
        "USER INPUT\n"
        "--------------------------------------------------------------------------------\n"
        f"{user_input.strip() if user_input else ''}\n\n"
        "--------------------------------------------------------------------------------\n"
        "INTERNAL/SYSTEM RESPONSE\n"
        "--------------------------------------------------------------------------------\n"
        f"{internal_str.strip()}\n\n"
        "--------------------------------------------------------------------------------\n"
        "FINAL RESPONSE GENERATED BY THE AI\n"
        "--------------------------------------------------------------------------------\n"
        f"{ai_resp_str.strip()}\n\n"
        "--------------------------------------------------------------------------------\n"
        "FINAL RESPONSE ACTUALLY SENT TO THE USER\n"
        "--------------------------------------------------------------------------------\n"
        f"{user_resp_str.strip()}\n"
        "================================================================================\n"
    )
    return log_content


def cleanup_old_logs(
    logs_dir: Optional[Path] = None,
    retention_days: Optional[int] = None,
    now: Optional[datetime] = None,
) -> List[Path]:
    """
    Automatically delete log files older than retention_days (default: 2 days).
    Returns list of deleted file paths.
    """
    target_dir = logs_dir or get_logs_dir()
    if not target_dir.exists():
        return []

    days = retention_days if retention_days is not None else getattr(settings, "log_retention_days", 2)
    cutoff = (now or datetime.now()) - timedelta(days=days)

    deleted_files: List[Path] = []
    try:
        for file_path in target_dir.glob("*.txt"):
            if not file_path.is_file():
                continue

            file_dt: Optional[datetime] = None
            # Match timestamp in filename: YYYY-MM-DD-HHMMSS
            match = re.match(r"^(\d{4}-\d{2}-\d{2})-(\d{2})(\d{2})(\d{2})", file_path.stem)
            if match:
                try:
                    date_part = match.group(1)
                    hour, minute, second = match.group(2), match.group(3), match.group(4)
                    file_dt = datetime.strptime(f"{date_part}-{hour}{minute}{second}", "%Y-%m-%d-%H%M%S")
                except ValueError:
                    file_dt = None

            if file_dt is None:
                # Fallback to filesystem modification time
                try:
                    mtime = file_path.stat().st_mtime
                    file_dt = datetime.fromtimestamp(mtime)
                except Exception:
                    file_dt = None

            if file_dt and file_dt < cutoff:
                try:
                    file_path.unlink()
                    deleted_files.append(file_path)
                    logger.debug(f"Deleted expired log file: {file_path.name} (age > {days} days)")
                except Exception as del_err:
                    logger.warning(f"Could not delete expired log file {file_path.name}: {del_err}")

    except Exception as e:
        logger.error(f"Error during log cleanup: {e}", exc_info=True)

    return deleted_files


def write_interaction_log(
    user_input: str,
    internal_response: Any,
    ai_response: str,
    user_response: Any,
    timestamp: Optional[datetime] = None,
    logs_dir: Optional[Path] = None,
    perform_cleanup: bool = True,
    retention_days: Optional[int] = None,
) -> Path:
    """
    Synchronously write interaction log file and trigger cleanup.
    Wrapped with exception handling so errors are logged and do not crash callers.
    """
    ts = timestamp or datetime.now()
    target_dir = logs_dir or get_logs_dir()

    log_path = _generate_log_filename(ts, target_dir)
    content = format_interaction_log(
        timestamp=ts,
        user_input=user_input,
        internal_response=internal_response,
        ai_response=ai_response,
        user_response=user_response,
    )

    try:
        log_path.write_text(content, encoding="utf-8")
        logger.info(f"Interaction logged to {log_path.name}")
    except Exception as e:
        logger.error(f"Failed to write interaction log to {log_path}: {e}", exc_info=True)

    if perform_cleanup:
        try:
            cleanup_old_logs(logs_dir=target_dir, retention_days=retention_days, now=ts)
        except Exception as e:
            logger.error(f"Failed to perform automated log cleanup: {e}", exc_info=True)

    return log_path


def log_interaction_background(
    background_tasks: Optional[BackgroundTasks],
    user_input: str,
    internal_response: Any,
    ai_response: str,
    user_response: Any,
    timestamp: Optional[datetime] = None,
    logs_dir: Optional[Path] = None,
    retention_days: Optional[int] = None,
) -> None:
    """
    Log interaction asynchronously so that response latency is not impacted.
    Uses FastAPI's BackgroundTasks if provided, otherwise delegates to a background thread.
    """
    ts = timestamp or datetime.now()

    if background_tasks is not None:
        background_tasks.add_task(
            write_interaction_log,
            user_input=user_input,
            internal_response=internal_response,
            ai_response=ai_response,
            user_response=user_response,
            timestamp=ts,
            logs_dir=logs_dir,
            perform_cleanup=True,
            retention_days=retention_days,
        )
    else:
        # Fallback to executor for non-FastAPI contexts
        _executor.submit(
            write_interaction_log,
            user_input=user_input,
            internal_response=internal_response,
            ai_response=ai_response,
            user_response=user_response,
            timestamp=ts,
            logs_dir=logs_dir,
            perform_cleanup=True,
            retention_days=retention_days,
        )
