from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The customer question or tile requirement query.",
        examples=["I need grey floor tiles for my bathroom. What do you recommend?"]
    )


class SourceItem(BaseModel):
    title: str = Field(..., description="Title of the matched product, page, or article")
    url: str = Field(..., description="Direct link on surfacestiles.co.uk")
    category: Optional[str] = Field(default=None, description="Category or topic")
    content_type: Optional[str] = Field(default=None, description="Type: product, policy, faq, blog, page")
    price: Optional[str] = Field(default=None, description="Price string if applicable")
    relevance_score: Optional[float] = Field(default=None, description="Cosine similarity score (0.0 to 1.0)")


class ResponseMeta(BaseModel):
    status: int = Field(default=1, description="Status indicator (1 for success)")
    message: str = Field(
        default="Successfully processed user measurements and preferences",
        description="Response status message"
    )


class ChatData(BaseModel):
    Response: Any = Field(..., description="Main response generated by the chatbot")
    sources: Optional[List[SourceItem]] = Field(
        default=None,
        description="Verified sources retrieved from website"
    )


class ChatResponse(BaseModel):
    meta: ResponseMeta = Field(default_factory=ResponseMeta, description="Response metadata")
    data: ChatData = Field(..., description="Response data payload containing Response")
    statusCode: int = Field(default=200, description="HTTP status code")


class HealthResponse(BaseModel):
    status: str
    document_count: int
    gemini_configured: bool
    embedding_model: str
    llm_model: str
    version: str = "1.0.0"


class ScrapeRequest(BaseModel):
    run_in_background: bool = Field(default=False, description="Run scrape asynchronously in background")


class ScrapeResponse(BaseModel):
    status: str
    message: str
    counts: Optional[Dict[str, int]] = None


class IngestRequest(BaseModel):
    force_reset: bool = Field(default=True, description="Whether to clear existing vector store before re-indexing")
    run_in_background: bool = Field(default=False, description="Run ingestion in background task")


class IngestResponse(BaseModel):
    status: str
    message: str
    chunks_indexed: int
